### ISSUE TITLE
Deployment Target ignored when building IPA

### ISSUE THREAD

**Issue by pimrie** [ionic-team/ionic-cloud#93]
Hi there,

When building a new iOS build we have the following set in config.xml:
`<preference name="deployment-target" value="9.0"/>`

This setting appears to be ignored as package states it supports iOS version 8.0 and above.

Thanks

Peter

**Comment by pimrie** [comment]
Any news?

**Comment by ericb** [comment]
@dwieeb can we verify this?

**Comment by dwieeb** [comment]
@pimrie Seems that `deployment-target` and `target-device` were being ignored and it has been fixed in cordova-ios 4.3.1: https://cordova.apache.org/announcements/2016/12/02/ios-release.html

Please try your build with cordova-ios 4.3.1. If you encounter other strange build errors, try 4.1.0. You can set the platform version as documented here: http://docs.ionic.io/services/package/#platform-version

**Comment by pimrie** [comment]
Thanks for the response, will try the new cordova-ios and see how it goes
